drop table inventory cascade;
drop table account cascade;
drop table recording cascade;
drop table instrument cascade;
DROP TABLE "quote" cascade;
DROP TABLE "accounttype"cascade;
DROP TABLE "user" cascade;
DROP TABLE "country" cascade;
DROP TABLE "rate" cascade;
DROP TABLE "currency" cascade;
DROP TABLE "registration" cascade;
drop table play_evolutions cascade;
